// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package vehicle

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"github.com/DAVFoundation/captain/protocols/types"
	"github.com/DAVFoundation/captain/protocols/davuser"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = types.GoUnusedProtection__
var _ = davuser.GoUnusedProtection__
// This structure is used to represent a state of a vehicle at a certain point in time
// 
// Attributes:
//  - Timestamp
//  - Coordinates
//  - Heading
//  - Height
//  - BatteryLevel
//  - Waypoints
//  - MissionStatus
type VehicleState struct {
  Timestamp types.Timestamp `thrift:"timestamp,1,required" db:"timestamp" json:"timestamp"`
  Coordinates *types.Coordinates `thrift:"coordinates,2,required" db:"coordinates" json:"coordinates"`
  Heading *int16 `thrift:"heading,3" db:"heading" json:"heading,omitempty"`
  Height *int16 `thrift:"height,4" db:"height" json:"height,omitempty"`
  BatteryLevel *int8 `thrift:"battery_level,5" db:"battery_level" json:"battery_level,omitempty"`
  Waypoints types.WayPoints `thrift:"waypoints,6" db:"waypoints" json:"waypoints,omitempty"`
  MissionStatus *string `thrift:"mission_status,7" db:"mission_status" json:"mission_status,omitempty"`
}

func NewVehicleState() *VehicleState {
  return &VehicleState{}
}


func (p *VehicleState) GetTimestamp() types.Timestamp {
  return p.Timestamp
}
var VehicleState_Coordinates_DEFAULT *types.Coordinates
func (p *VehicleState) GetCoordinates() *types.Coordinates {
  if !p.IsSetCoordinates() {
    return VehicleState_Coordinates_DEFAULT
  }
return p.Coordinates
}
var VehicleState_Heading_DEFAULT int16
func (p *VehicleState) GetHeading() int16 {
  if !p.IsSetHeading() {
    return VehicleState_Heading_DEFAULT
  }
return *p.Heading
}
var VehicleState_Height_DEFAULT int16
func (p *VehicleState) GetHeight() int16 {
  if !p.IsSetHeight() {
    return VehicleState_Height_DEFAULT
  }
return *p.Height
}
var VehicleState_BatteryLevel_DEFAULT int8
func (p *VehicleState) GetBatteryLevel() int8 {
  if !p.IsSetBatteryLevel() {
    return VehicleState_BatteryLevel_DEFAULT
  }
return *p.BatteryLevel
}
var VehicleState_Waypoints_DEFAULT types.WayPoints

func (p *VehicleState) GetWaypoints() types.WayPoints {
  return p.Waypoints
}
var VehicleState_MissionStatus_DEFAULT string
func (p *VehicleState) GetMissionStatus() string {
  if !p.IsSetMissionStatus() {
    return VehicleState_MissionStatus_DEFAULT
  }
return *p.MissionStatus
}
func (p *VehicleState) IsSetCoordinates() bool {
  return p.Coordinates != nil
}

func (p *VehicleState) IsSetHeading() bool {
  return p.Heading != nil
}

func (p *VehicleState) IsSetHeight() bool {
  return p.Height != nil
}

func (p *VehicleState) IsSetBatteryLevel() bool {
  return p.BatteryLevel != nil
}

func (p *VehicleState) IsSetWaypoints() bool {
  return p.Waypoints != nil
}

func (p *VehicleState) IsSetMissionStatus() bool {
  return p.MissionStatus != nil
}

func (p *VehicleState) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetTimestamp bool = false;
  var issetCoordinates bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetTimestamp = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
      issetCoordinates = true
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
    case 5:
      if err := p.ReadField5(iprot); err != nil {
        return err
      }
    case 6:
      if err := p.ReadField6(iprot); err != nil {
        return err
      }
    case 7:
      if err := p.ReadField7(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetTimestamp{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Timestamp is not set"));
  }
  if !issetCoordinates{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Coordinates is not set"));
  }
  return nil
}

func (p *VehicleState)  ReadField1(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI64(); err != nil {
  return thrift.PrependError("error reading field 1: ", err)
} else {
  temp := types.Timestamp(v)
  p.Timestamp = temp
}
  return nil
}

func (p *VehicleState)  ReadField2(iprot thrift.TProtocol) error {
  p.Coordinates = &types.Coordinates{}
  if err := p.Coordinates.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Coordinates), err)
  }
  return nil
}

func (p *VehicleState)  ReadField3(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI16(); err != nil {
  return thrift.PrependError("error reading field 3: ", err)
} else {
  p.Heading = &v
}
  return nil
}

func (p *VehicleState)  ReadField4(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI16(); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.Height = &v
}
  return nil
}

func (p *VehicleState)  ReadField5(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadByte(); err != nil {
  return thrift.PrependError("error reading field 5: ", err)
} else {
  temp := int8(v)
  p.BatteryLevel = &temp
}
  return nil
}

func (p *VehicleState)  ReadField6(iprot thrift.TProtocol) error {
  _, size, err := iprot.ReadListBegin()
  if err != nil {
    return thrift.PrependError("error reading list begin: ", err)
  }
  tSlice := make(types.WayPoints, 0, size)
  p.Waypoints =  tSlice
  for i := 0; i < size; i ++ {
    _elem0 := &types.Coordinates{}
    if err := _elem0.Read(iprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem0), err)
    }
    p.Waypoints = append(p.Waypoints, _elem0)
  }
  if err := iprot.ReadListEnd(); err != nil {
    return thrift.PrependError("error reading list end: ", err)
  }
  return nil
}

func (p *VehicleState)  ReadField7(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 7: ", err)
} else {
  p.MissionStatus = &v
}
  return nil
}

func (p *VehicleState) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("VehicleState"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
    if err := p.writeField3(oprot); err != nil { return err }
    if err := p.writeField4(oprot); err != nil { return err }
    if err := p.writeField5(oprot); err != nil { return err }
    if err := p.writeField6(oprot); err != nil { return err }
    if err := p.writeField7(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VehicleState) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("timestamp", thrift.I64, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:timestamp: ", p), err) }
  if err := oprot.WriteI64(int64(p.Timestamp)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.timestamp (1) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:timestamp: ", p), err) }
  return err
}

func (p *VehicleState) writeField2(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("coordinates", thrift.STRUCT, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:coordinates: ", p), err) }
  if err := p.Coordinates.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Coordinates), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:coordinates: ", p), err) }
  return err
}

func (p *VehicleState) writeField3(oprot thrift.TProtocol) (err error) {
  if p.IsSetHeading() {
    if err := oprot.WriteFieldBegin("heading", thrift.I16, 3); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:heading: ", p), err) }
    if err := oprot.WriteI16(int16(*p.Heading)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.heading (3) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 3:heading: ", p), err) }
  }
  return err
}

func (p *VehicleState) writeField4(oprot thrift.TProtocol) (err error) {
  if p.IsSetHeight() {
    if err := oprot.WriteFieldBegin("height", thrift.I16, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:height: ", p), err) }
    if err := oprot.WriteI16(int16(*p.Height)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.height (4) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:height: ", p), err) }
  }
  return err
}

func (p *VehicleState) writeField5(oprot thrift.TProtocol) (err error) {
  if p.IsSetBatteryLevel() {
    if err := oprot.WriteFieldBegin("battery_level", thrift.BYTE, 5); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:battery_level: ", p), err) }
    if err := oprot.WriteByte(int8(*p.BatteryLevel)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.battery_level (5) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 5:battery_level: ", p), err) }
  }
  return err
}

func (p *VehicleState) writeField6(oprot thrift.TProtocol) (err error) {
  if p.IsSetWaypoints() {
    if err := oprot.WriteFieldBegin("waypoints", thrift.LIST, 6); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:waypoints: ", p), err) }
    if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Waypoints)); err != nil {
      return thrift.PrependError("error writing list begin: ", err)
    }
    for _, v := range p.Waypoints {
      if err := v.Write(oprot); err != nil {
        return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
      }
    }
    if err := oprot.WriteListEnd(); err != nil {
      return thrift.PrependError("error writing list end: ", err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 6:waypoints: ", p), err) }
  }
  return err
}

func (p *VehicleState) writeField7(oprot thrift.TProtocol) (err error) {
  if p.IsSetMissionStatus() {
    if err := oprot.WriteFieldBegin("mission_status", thrift.STRING, 7); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:mission_status: ", p), err) }
    if err := oprot.WriteString(string(*p.MissionStatus)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.mission_status (7) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 7:mission_status: ", p), err) }
  }
  return err
}

func (p *VehicleState) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VehicleState(%+v)", *p)
}

// Attributes:
//  - VehicleId
//  - Model
//  - Coordinates
//  - Rating
//  - MissionsCompleted
//  - MissionsCompleted_7Days
type VehicleDetails struct {
  VehicleId *davuser.DAVUser `thrift:"vehicleId,1,required" db:"vehicleId" json:"vehicleId"`
  Model *string `thrift:"model,2" db:"model" json:"model,omitempty"`
  Coordinates *types.Coordinates `thrift:"coordinates,3" db:"coordinates" json:"coordinates,omitempty"`
  Rating *float64 `thrift:"rating,4" db:"rating" json:"rating,omitempty"`
  MissionsCompleted *int16 `thrift:"missions_completed,5" db:"missions_completed" json:"missions_completed,omitempty"`
  MissionsCompleted_7Days *int16 `thrift:"missions_completed_7_days,6" db:"missions_completed_7_days" json:"missions_completed_7_days,omitempty"`
}

func NewVehicleDetails() *VehicleDetails {
  return &VehicleDetails{}
}

var VehicleDetails_VehicleId_DEFAULT *davuser.DAVUser
func (p *VehicleDetails) GetVehicleId() *davuser.DAVUser {
  if !p.IsSetVehicleId() {
    return VehicleDetails_VehicleId_DEFAULT
  }
return p.VehicleId
}
var VehicleDetails_Model_DEFAULT string
func (p *VehicleDetails) GetModel() string {
  if !p.IsSetModel() {
    return VehicleDetails_Model_DEFAULT
  }
return *p.Model
}
var VehicleDetails_Coordinates_DEFAULT *types.Coordinates
func (p *VehicleDetails) GetCoordinates() *types.Coordinates {
  if !p.IsSetCoordinates() {
    return VehicleDetails_Coordinates_DEFAULT
  }
return p.Coordinates
}
var VehicleDetails_Rating_DEFAULT float64
func (p *VehicleDetails) GetRating() float64 {
  if !p.IsSetRating() {
    return VehicleDetails_Rating_DEFAULT
  }
return *p.Rating
}
var VehicleDetails_MissionsCompleted_DEFAULT int16
func (p *VehicleDetails) GetMissionsCompleted() int16 {
  if !p.IsSetMissionsCompleted() {
    return VehicleDetails_MissionsCompleted_DEFAULT
  }
return *p.MissionsCompleted
}
var VehicleDetails_MissionsCompleted_7Days_DEFAULT int16
func (p *VehicleDetails) GetMissionsCompleted_7Days() int16 {
  if !p.IsSetMissionsCompleted_7Days() {
    return VehicleDetails_MissionsCompleted_7Days_DEFAULT
  }
return *p.MissionsCompleted_7Days
}
func (p *VehicleDetails) IsSetVehicleId() bool {
  return p.VehicleId != nil
}

func (p *VehicleDetails) IsSetModel() bool {
  return p.Model != nil
}

func (p *VehicleDetails) IsSetCoordinates() bool {
  return p.Coordinates != nil
}

func (p *VehicleDetails) IsSetRating() bool {
  return p.Rating != nil
}

func (p *VehicleDetails) IsSetMissionsCompleted() bool {
  return p.MissionsCompleted != nil
}

func (p *VehicleDetails) IsSetMissionsCompleted_7Days() bool {
  return p.MissionsCompleted_7Days != nil
}

func (p *VehicleDetails) Read(iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetVehicleId bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if err := p.ReadField1(iprot); err != nil {
        return err
      }
      issetVehicleId = true
    case 2:
      if err := p.ReadField2(iprot); err != nil {
        return err
      }
    case 3:
      if err := p.ReadField3(iprot); err != nil {
        return err
      }
    case 4:
      if err := p.ReadField4(iprot); err != nil {
        return err
      }
    case 5:
      if err := p.ReadField5(iprot); err != nil {
        return err
      }
    case 6:
      if err := p.ReadField6(iprot); err != nil {
        return err
      }
    default:
      if err := iprot.Skip(fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetVehicleId{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field VehicleId is not set"));
  }
  return nil
}

func (p *VehicleDetails)  ReadField1(iprot thrift.TProtocol) error {
  p.VehicleId = &davuser.DAVUser{}
  if err := p.VehicleId.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.VehicleId), err)
  }
  return nil
}

func (p *VehicleDetails)  ReadField2(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Model = &v
}
  return nil
}

func (p *VehicleDetails)  ReadField3(iprot thrift.TProtocol) error {
  p.Coordinates = &types.Coordinates{}
  if err := p.Coordinates.Read(iprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Coordinates), err)
  }
  return nil
}

func (p *VehicleDetails)  ReadField4(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadDouble(); err != nil {
  return thrift.PrependError("error reading field 4: ", err)
} else {
  p.Rating = &v
}
  return nil
}

func (p *VehicleDetails)  ReadField5(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI16(); err != nil {
  return thrift.PrependError("error reading field 5: ", err)
} else {
  p.MissionsCompleted = &v
}
  return nil
}

func (p *VehicleDetails)  ReadField6(iprot thrift.TProtocol) error {
  if v, err := iprot.ReadI16(); err != nil {
  return thrift.PrependError("error reading field 6: ", err)
} else {
  p.MissionsCompleted_7Days = &v
}
  return nil
}

func (p *VehicleDetails) Write(oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin("VehicleDetails"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(oprot); err != nil { return err }
    if err := p.writeField2(oprot); err != nil { return err }
    if err := p.writeField3(oprot); err != nil { return err }
    if err := p.writeField4(oprot); err != nil { return err }
    if err := p.writeField5(oprot); err != nil { return err }
    if err := p.writeField6(oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *VehicleDetails) writeField1(oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin("vehicleId", thrift.STRUCT, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:vehicleId: ", p), err) }
  if err := p.VehicleId.Write(oprot); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.VehicleId), err)
  }
  if err := oprot.WriteFieldEnd(); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:vehicleId: ", p), err) }
  return err
}

func (p *VehicleDetails) writeField2(oprot thrift.TProtocol) (err error) {
  if p.IsSetModel() {
    if err := oprot.WriteFieldBegin("model", thrift.STRING, 2); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:model: ", p), err) }
    if err := oprot.WriteString(string(*p.Model)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.model (2) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 2:model: ", p), err) }
  }
  return err
}

func (p *VehicleDetails) writeField3(oprot thrift.TProtocol) (err error) {
  if p.IsSetCoordinates() {
    if err := oprot.WriteFieldBegin("coordinates", thrift.STRUCT, 3); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:coordinates: ", p), err) }
    if err := p.Coordinates.Write(oprot); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Coordinates), err)
    }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 3:coordinates: ", p), err) }
  }
  return err
}

func (p *VehicleDetails) writeField4(oprot thrift.TProtocol) (err error) {
  if p.IsSetRating() {
    if err := oprot.WriteFieldBegin("rating", thrift.DOUBLE, 4); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:rating: ", p), err) }
    if err := oprot.WriteDouble(float64(*p.Rating)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.rating (4) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 4:rating: ", p), err) }
  }
  return err
}

func (p *VehicleDetails) writeField5(oprot thrift.TProtocol) (err error) {
  if p.IsSetMissionsCompleted() {
    if err := oprot.WriteFieldBegin("missions_completed", thrift.I16, 5); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:missions_completed: ", p), err) }
    if err := oprot.WriteI16(int16(*p.MissionsCompleted)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.missions_completed (5) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 5:missions_completed: ", p), err) }
  }
  return err
}

func (p *VehicleDetails) writeField6(oprot thrift.TProtocol) (err error) {
  if p.IsSetMissionsCompleted_7Days() {
    if err := oprot.WriteFieldBegin("missions_completed_7_days", thrift.I16, 6); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:missions_completed_7_days: ", p), err) }
    if err := oprot.WriteI16(int16(*p.MissionsCompleted_7Days)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.missions_completed_7_days (6) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 6:missions_completed_7_days: ", p), err) }
  }
  return err
}

func (p *VehicleDetails) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("VehicleDetails(%+v)", *p)
}

